export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

export const TRY_AUTH = 'TRY_AUTH';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';

export const KYC_SET = 'KYC_SET';
export const KYC_SET_DETAILS = 'KYC_SET_DETAILS';
export const PAN_STATUS = 'PAN_STATUS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const KYC_UNSET_DETAILS = 'KYC_UNSET_DETAILS';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const SCREEN_START_LOADING = 'SCREEN_START_LOADING';
export const SCREEN_STOP_LOADING = 'SCREEN_STOP_LOADING';

export const SET_REQUESTING_COMPANY_DETAILS = 'SET_REQUESTING_COMPANY_DETAILS';
